### PR TITLE
Fix descriptions for optional paramters and use schema default for booleans.

### PR DESCRIPTION
**Pull request by luqmana**
Fixes:
- We were attaching the object's description to its optional parameters. Fixed that by keeping the parameter's SchemaData if present.
- Update the default generated for booleans if the schema specified it as `true`.

Also update our openapiv3 dep to point to the crates.io version instead of jess' fork. There is one new unhandled case but that's unused for our spec and there were no differences in the generated code.

### CODE REVIEW

**Comment by karencfv** [comment]
Thanks @luqmana! Could you run `make generate` and commit the changes?

Also a heads up. We'll soon be changing this repo to use the code generated from progenitor (sneak peak here -> https://github.com/oxidecomputer/oxide-sdk-rust/blob/main/oxide_api/src/lib.rs). So if you're building something new I highly recommend you use the progenitor generated code!

**Comment by luqmana** [comment]
> Thanks @luqmana! Could you run `make generate` and commit the changes?

Re-generated & pushed!

> Also a heads up. We'll soon be changing this repo to use the code generated from progenitor (sneak peak here -> https://github.com/oxidecomputer/oxide-sdk-rust/blob/main/oxide_api/src/lib.rs). So if you're building something new I highly recommend you use the progenitor generated code!

Yup, I just wanted to update the existing client in the meantime. I am looking forward to the progenitor based one!

**Comment by luqmana** [comment]
Should I increment the version also?

**Review by karencfv — APPROVED** [review]
> Yup, I just wanted to update the existing client in the meantime

Thank you!!! 🙇‍♀️ 😊 

No worries about updating the version. I generally like to update versions on their own commit as much as possible in case there is a need to revert commits (unlikely in this case but I'm just always paranoid 😄 )

**Pull request merged**
