### PR TITLE
Support Option<u64> query params (for nexus's instance serial console endpoint)

### PR DESCRIPTION
**Pull request by lifning**
This adds support for passing Option<u64> parameters, needed by `serial_get` wherein passing `0` is meaningful and not the same as not providing the parameter at all (i.e. passing `None` in the generated API).

To catch up with other omicron changes, this also includes some workarounds to get the generated code compiling with `GlobalImageCreate` and `SamlIdentityProviderCreate`, which have enum fields with no `Default`, as well as emitting an `impl fmt::Display for Distribution` (name-version, e.g. "ubuntu-22.04") such that `GlobalImageCreate` can derive `Tabled`.

### CODE REVIEW

**Review by karencfv — COMMENTED** [review]
Heya @lifning, Thanks a bunch for working on this, and fixing the bug! 🙇‍♀️ 

Just one small thing is missing. Could you update the version to `0.1.0-rc.37` on `VERSION.txt` as well, and run `make generate`?

**Comment by lifning** [comment]
> Heya @lifning, Thanks a bunch for working on this, and fixing the bug! bowing_woman
> 
> Just one small thing is missing. Could you update the version to `0.1.0-rc.37` on `VERSION.txt` as well, and run `make generate`?

Ah right! Was manually invoking the generator while iterating on it and forgot to re-run the make target properly. Fixed the .txt, everything else is the same after a proper `make generate` run (incidentally, for some reason `make` doesn't like the Makefile on my helios box -- `make: Fatal error in reader: Makefile, line 2: Unexpected end of line seen` -- so I had to run that from Linux)

Thanks!

**Comment by rmustacc** [comment]
@lifning I expect you may need to explicitly invoke `gmake` to make that work on illumos. As the unadorned `make` is probably the illumos `dmake` implementation and not the GNU one (similar to `bmake` issues on *BSD).

**Comment by lifning** [comment]
> @lifning I expect you may need to explicitly invoke `gmake` to make that work on illumos. As the unadorned `make` is probably the illumos `dmake` implementation and not the GNU one (similar to `bmake` issues on *BSD).

/bin/gmake and /opt/local/bin/gmake both hate it, they're just a little more verbose about it...
```
rm -f /home/lifning/ws/oxide.rs/spec.json
make /home/lifning/ws/oxide.rs/spec.json
make: Fatal error in reader: Makefile, line 2: Unexpected end of line seen
Current working directory /home/lifning/ws/oxide.rs
gmake: *** [Makefile:25: update-specs] Error 1
```

Oh, wait a minute! Okay, I've got the fix...
```diff
diff --git a/Makefile b/Makefile
index 3305412..e490c4d 100644
--- a/Makefile
+++ b/Makefile
@@ -22,7 +22,7 @@ clean-spec:
 update: update-specs

 update-specs: clean-spec
-       make $(SPEC)
+       $(MAKE) $(SPEC)

 $(SPEC):
        curl -sSL $(SPEC_REMOTE) -o $@
```

**Review by karencfv — APPROVED** [review]
Woohoo thanks! Not sure why the tests didn't run 🤔 But I can confirm they passed locally

**Comment by karencfv** [comment]
@lifning Just released the new version with your changes. Thanks again!

**Pull request merged**
